[package]
name = "tasktui"
version = "0.1.0"
edition = "2024"
authors = ["Fankrits <fankritsadajra@gmail.com>"]
description = "A blazing-fast, lightweight, and modern terminal task manager and system monitor built with Rust and Ratatui."
license = "MIT"
readme = "README.md"
repository = "https://github.com/Fankrits/TaskTUI"
keywords = ["tui", "system-monitor", "task-manager", "process-viewer", "ratatui"]
categories = ["command-line-utilities", "system::monitoring"]

[dependencies]
anyhow = "1.0.104"
crossterm = { version = "0.29.0", default-features = false, features = ["bracketed-paste", "events"] }
netstat2 = "0.11.2"
ratatui = { version = "0.30.2", default-features = false, features = ["crossterm"] }
sysinfo = { version = "0.39.6", default-features = false, features = ["system", "network", "disk", "user"] }
unicode-width = "0.2.2"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
